version: 2

sources:
  - name: staging
    description: A staged copy 
    schema: de_zoomcamp_project
    tables:
      - name: nyc_inspect_data_partitioned_clustered

models:
  - name: stg_nyc_inspect_data
    description: >
      The dataset contains every sustained or not yet adjudicated violation citation 
      from every full or special program inspection conducted up to three years prior 
      to the most recent inspection for restaurants and college cafeterias in NYC.
    columns:
      - name: camis
        description: This is an unique identifier for the entity (restaurant). ten digit integer, static per restaurant permit.
        tests:
            - unique:
                severity: warn
            - not_null:
                severity: warn

      - name: dba
        description: This field represents the name (doing business as) of the entity (restaurant). Public business name, may change at discretion of restaurant owner.

      - name: boro
        description: > 
          Borough in which the entity (restaurant) is located..• 1 = MANHATTAN • 2 = BRONX • 3 = BROOKLYN 
          • 4 = QUEENS • 5 = STATEN ISLAND • Missing. NOTE: There may be discrepancies between 
          zip code and listed boro due to differences in an establishment's mailing address 
          and physical location.
      - name: building
        description: >
          Building number for establishment (restaurant) location
      - name: street
        description: >
          Street name for establishment (restaurant) location.
      - name: zipcode
        description: Zip code of establishment (restaurant) location 

      - name: phone
        description: >
          Phone Number. Phone number provided by restaurant owner/manager
      - name: cuisine_description
        description:  This field describes the entity (restaurant) cuisine.Optional field provided by provided by restaurant owner/manager

      - name: inspection_date
        description: This field represents the date of inspection. NOTE Inspection dates of 1/1/1900 mean an establishment has not yet had an inspection

      - name: action
        description: >
          This field represents the actions that is associated with each restaurant inspection. .
           • Violations were cited in the following area(s). • No violations were recorded at the 
           time of this inspection. • Establishment re-opened by DOHMH • Establishment re-closed by 
           DOHMH • Establishment Closed by DOHMH. Violations were cited in the following area(s)
            and those requiring immediate action were addressed. • "Missing" = not yet inspected.

      - name: violation_code
        description: >
          Violation code associated with an establishment (restaurant) inspection
      - name: violation_description
        description: >
          Violation description associated with an establishment (restaurant) inspection
      - name: critical_flag
        description: Indicator of critical violation. "• Critical • Not Critical • Not Applicable". Critical violations are those most likely to contribute to food-borne illness

      - name: score
        description: Total score for a particular inspection. Scores are updated based on adjudication results

      - name: grade
        description: Grade associated with the inspection. • N = Not Yet Graded• A = Grade A • B = Grade B• C = Grade C• Z = Grade Pending• P= Grade Pending issued on re-opening following an initial inspection that resulted in a closure

      - name: grade_date
        description: The date when the current grade was issued to the entity (restaurant)

      - name: record_date 
        description: The date when the extract was run to produce this data set

      - name: inspection_type
        description: A combination of the inspection program and the type of inspection performed. See Data Dictionary for full list of expected values

      - name: latitude
        description: The latitude column is of the number datatype.

      - name: longitude
        description: The longitude column is of the number datatype.

      - name: community_board
        description: NA

      - name: council_district
        description: NA

      - name: census_tract 
        description: NA

      - name: bin
        description:  NA

      - name: bbl
        description: NA

      - name: nta
        description: NA

      - name: location_point1
        description: NA